Added how-to article transfer a project to another organisation
divio/user-support-guides pull request #12
Opened 2021-02-09 16:33 UTC by mebdivio

2021-02-10 16:50 UTC, evildmp requested changes

2021-02-10 16:50 UTC, evildmp commented on transfer-organisation.rst
> +To transfer a project to another organisation, first you must cancel its subscription via the Subscription view. A project cannot be transferred while it has a subscription applied.
Check column length please

2021-02-10 16:50 UTC, evildmp commented on transfer-organisation.rst
> +    if you don't want to interrupt the subscription, please contact Divio support and we can transfer the project
Capitalisation - if.

2021-02-10 16:50 UTC, evildmp commented on transfer-organisation.rst
> +.. image:: /images/options-menu-project-view.png
Use both images:

```
.. image:: /images/options-menu-organisations-view.png
   :alt: 'options menu'
   :width: 685

or in the project view:

.. image:: /images/options-menu-project-view.png
   :alt: 'options menu'
   :width: 690
```

2021-02-10 20:33 UTC, mebdivio commented on transfer-organisation.rst
> +    if you don't want to interrupt the subscription, please contact Divio support and we can transfer the project
Done

2021-02-10 20:33 UTC, mebdivio commented on transfer-organisation.rst
> +.. image:: /images/options-menu-project-view.png
Done

2021-02-10 20:34 UTC, mebdivio commented on transfer-organisation.rst
> +To transfer a project to another organisation, first you must cancel its subscription via the Subscription view. A project cannot be transferred while it has a subscription applied.
Done

2021-02-11 09:06 UTC, evildmp commented on transfer-organisation.rst
> +.. note:: For projects with business subscription only:
_Business subcriptions_

2021-02-11 09:12 UTC, mebdivio commented on transfer-organisation.rst
> +.. note:: For projects with business subscription only:
Done

2021-02-11 10:18 UTC, merged