Added Moving off Divio article
divio/user-support-guides pull request #18
Opened 2021-02-16 16:05 UTC by mebdivio

2021-02-23 09:46 UTC, evildmp requested changes

2021-02-23 09:46 UTC, evildmp commented on index.rst
> +    move-off-divio
Please change to `leaving-divio`

2021-02-23 09:46 UTC, evildmp commented on move-off-divio.rst
> +Moving off Divio
Title should be `Leaving Divio`

2021-02-25 16:51 UTC, mebdivio commented on index.rst
> +    move-off-divio
Done

2021-02-25 16:52 UTC, mebdivio commented on move-off-divio.rst
> +Moving off Divio
Done

2021-02-25 17:05 UTC, merged