duplicating project and how-to initial commit.
divio/user-support-guides pull request #5
Opened 2021-01-29 11:07 UTC by mebdivio

2021-01-29 12:59 UTC, evildmp requested changes
Please change the commit message. The message should say what was changed in this commit. In this case:

    Added how-to and essential knowledge articles on project duplication

2021-01-29 12:59 UTC, evildmp commented on copy-project.rst
> +From the *Copy type* select the appropriate duplication action, Copy, Fork or Mirror. Refer to :ref:`duplicating projects <project-duplication>`
Please set your editor to re-wrap lines at 100 or 120 columns, and reformat paragraphs to fit into that limit.

2021-01-29 12:59 UTC, evildmp commented on index.rst
> +    Duplicate a project <copy-project>
Move this up so that all `xxxx a project` entries are listed together. _Duplicate_ should be before _delete_.

2021-01-29 12:59 UTC, evildmp commented on copy-project.rst
> +.. _copy-project:
use the form:

    .. _how-to-[...]:

In this case it should be:

    .. _how-to-project-duplicate:

2021-01-29 12:59 UTC, evildmp commented on project-duplication.rst
> +.. _project-duplication:
.. _knowledge-project-duplicate:

2021-02-01 13:40 UTC, evildmp commented
@mebdivio Unfortunately your latest commit fd724e09e79ecbc3b1f3f5aeb059a51936c4aad1 changes many files, not just the three that were the subject of this pull request.

Pull requests should contain only a particular change. A formatting change should be made in a separate action from a content change. In this commit, you also make changes to headings, which should be done separately.

In addition, the commit does not change the layout correctly. Lines should be wrapped to 100 or 120 columns. This commit appears to remove line wrapping.

The best thing would be to revert this commit altogether, and try again, changing _only_ the files in the first commit.

2021-02-05 14:08 UTC, closed without merging

2021-02-05 14:08 UTC, mebdivio commented
Done separately